[tool.ruff]
select = ["ALL"]

ignore = ["ANN101"] # missing-type-self

[tool.ruff.per-file-ignores]
"cli.py" = ["T201"]   # print statement
"setup.py" = ["T201"] # print statement
"tests/*" = ["S101"]  # assert
